### ISSUE TITLE
Migration generator template does not escape table names

### ISSUE THREAD

**Issue by navigator-dev** [Jujulego/nx-typeorm-plugin#7]
I tried using this library out-of-the-box with our repo and everything worked great except the generated migrations were invalid. The template file isn't doing any escaping and since table names in MySQL are surrounded by backticks things get a little ugly.

Below is how I'm getting around it, but I'm sure there's a better way -- I have 0 experience with EJS.

Sorry I didn't fork the repo and do a PR or anything!

\_\_number\_\_-\_\_fileName\_\_.migration.ts\_\_tmpl\_\_:
```
import { MigrationInterface, QueryRunner } from 'typeorm';

export class <%= className %><%= number %>Migration implements MigrationInterface {
  name = '<%= className %><%= timestamp %>'

  public async up(queryRunner: QueryRunner): Promise<void> {
    <% for (const { query } of sql.upQueries) { %>
      await queryRunner.query('<%- query.replace(/'/g, "\\'") %>');
    <% } %>
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    <% for (const { query } of sql.downQueries) { %>
      await queryRunner.query('<%- query.replace(/'/g, "\\'") %>');
    <% } %>
  }
}

```

**Comment by Jujulego** [comment]
First, thank's for your return ! You're the first one !

I mostly use postgresql, so I never tried it with mysql ...
You're solution looks good, but i will look in the typeorm cli code, to see what they do in such case.

Don't worry for the fork, but you know it's really easy with github ;)

Thank's again !
